### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by bootstraponline** [wuntee/otertool#4]
- https://github.com/wuntee/otertool/commits/3c21ba77c57007a6468ca8f4eb921432cca6144f/src/main/java/com/wuntee/oter/smali/SmaliWorkshop.java
- https://github.com/wuntee/otertool/commits/master/src/main/java/com/wuntee/oter/smali/SmaliWorkshop.java

I just spent a few hours debugging why otertool is producing invalid certs. What happened to the fix in #2? It's no longer in master.

**Comment by wuntee** [comment]
ugh - im really sorry. i do not use GIT much and had to delete the whole previous repo and re create it... i hate git. it should be fixed now.
