### ISSUE TITLE
default height of ConfigurationDialog is two small

### ISSUE THREAD

**Issue by terry2012** [wuntee/otertool#5]
thus I cannot see the "save" and "cancel" button... Actually I didnt realize there were button until I saw an variable named "btnSave"...

My machine environment is: Ubuntu 11.04 64-bit

related code snippet should be located in createContents() of ConfigurationDialog class:
private void createContents() {
    shell = new Shell(getParent(), SWT.DIALOG_TRIM | SWT.RESIZE);
    shell.setMinimumSize(new Point(450, 286));
    shell.setSize(450, 394);
    shell.setText("Configuration");

**Comment by terry2012** [comment]
wasting time to install maven, terrible... so many libs... :-(

**Comment by wuntee** [comment]
Ah - ya, I remember that. I will try and get the updated today. I
develop on osx and it works fine. As for a workaround I think the
dialog is realizable if you put a mouse in the bottom right corner.

Mathew Rowley

On Aug 1, 2012, at 6:17, terry2012
reply@reply.github.com
wrote:

**Comment by terry2012** [comment]
yeah. I had found that, thus I didnt compile the source code. :-)

**Comment by wuntee** [comment]
By any chance, do you know what an acceptable size would be on Linux?
I don't have a dev environment set up right now...

Mathew Rowley

On Aug 1, 2012, at 9:31, terry2012
reply@reply.github.com
wrote:

**Comment by terry2012** [comment]
guess 414?
according to shell.setSize(450, 394);

**Comment by terry2012** [comment]
you may find a better layout to cover all child component, e.g. relative layout
However, I do not have experience in j2se gui programming, not capable to help you :(

**Comment by wuntee** [comment]
Hmm - which version of otertool are you running? I just tested the x86
linux version and it works fine. Make sure you have the most recent package:

linux-x86:
https://github.com/wuntee/otertool/blob/master/release/current/oter-linux-x86.tar.gz?raw=true
linux-x96_64:
https://github.com/wuntee/otertool/blob/master/release/current/oter-linux-x86_64.tar.gz?raw=true
osx:
https://github.com/wuntee/otertool/blob/master/release/current/oter-osx.tar.gz?raw=true

On Wed, Aug 1, 2012 at 9:50 AM, terry2012 <
reply@reply.github.com

**Comment by bootstraponline** [comment]
I tested on Ubuntu and it works for me.

**Comment by terry2012** [comment]
Hi. wuntee,

Yeah. I use this one, https://github.com/wuntee/otertool/blob/master/release/current/oter-linux-x86_64.tar.gz?raw=true
And my monitor is big, 1920*1080. Maybe this reason?

**Comment by bootstraponline** [comment]
My monitor is small so it could be specific to large monitors.

**Comment by wuntee** [comment]
I have a large monitor and it seems to be working fine. Could you provide a
screenshot of what was seen?

On Thu, Aug 2, 2012 at 12:20 PM, bootstraponline <
reply@reply.github.com

**Comment by wuntee** [comment]
Actually - nm, I think I just figured it out. It's related to the minimum
height of the window. I will fix and update today.

**Comment by wuntee** [comment]
fixed

**Comment by terry2012** [comment]
thanks, wuntee.
